version: '3.7'

services:
  toughts_database:
    image: postgres
    container_name: toughts_database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=toughts_db
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: toughts_api
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - toughts_database
    depends_on: 
      - toughts_database
volumes:
  pgdata:
    driver: local